version: "3.7"
services:
  zookeeper:
    container_name: zookeeper
    build:
      context: .
      dockerfile: Dockerfile
    image: comchangs/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
networks:
  default:
    external:
      name: comchangs
  comchangs:
    driver: bridge
